version: "3.7"

volumes:
  csbirdvolume:
    name: cs-bird-volume
  grafanavolume:
    name: grafana-volume

networks:
  csbirdnetwork:
    name: cs-bird-network

services:
  tsdb:
    image: timescale/timescaledb:latest-pg13
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - csbirdvolume:/var/lib/postgresql/data
    networks:
      - csbirdnetwork
  pgadmin:
    image: thajeztah/pgadmin4
    restart: on-failure
    depends_on:
      - tsdb
    ports:
      - 5050:5050
    networks:
      - csbirdnetwork
    env_file:
      - .env
  # grafana:
  #   image: grafana/grafana:latest
  #   networks:
  #     - csbirdnetwork
  #   ports:
  #     - 3002:3000
  #   volumes:
  #     - grafanavolume:/var/lib/grafana
  csbird:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - tsdb
    volumes:
      - ./:/app
    networks:
      - csbirdnetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/crawler_entrypoint.sh"]
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - tsdb
    volumes:
      - ./:/app
    ports:
      - 8081:8081
    networks:
      - csbirdnetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/api_entrypoint.sh"]
